In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("linear_reg_area_data_v1.csv")

In [3]:
df

Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  723000

# Model Fitting 

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['Area']],df.Price)
prediction_input = np.array(3300).reshape(1, -1)

In [5]:
df.shape

(5, 2)

In [7]:
model.predict(prediction_input)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628291.09589041])

### saving model using pickle

In [8]:
import pickle

In [9]:
with open("pickle_model",'wb') as f:
    pickle.dump(model,f)

In [10]:
with open('pickle_model','rb') as f:
    mp = pickle.load(f)

### predicting with pickle model

In [11]:
mp.predict(prediction_input)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628291.09589041])

### saving model using joblib

In [12]:
import joblib

In [13]:
with open("joblib_model",'wb') as f:
    joblib.dump(model,f)

In [14]:
with open("joblib_model",'rb') as f:
    joblib_model = joblib.load(f)

### prediction using joblib model

In [33]:
joblib_model.predict(prediction_input)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628291.09589041])